# Model to analyze replacement of Russian imports by LNG

- no network conversion used
- analysis of the impact of LNG import capacity increasement

### Import packages

In [233]:
import gurobipy as gp
from gurobipy import GRB
import pandas as pd
import networkx as nx
import os

### Import Data

In [234]:
# Specify the path to your Excel file
input_file_path = os.path.join('..', '..','01_data', '01_input_data', '02_processed')
#excel_file_path = '\Data_update.xlsx'
excel_file_path = '\Data_update_methane_LNG_test.xlsx'

input_file_path  = input_file_path + excel_file_path
full_input_path = os.path.abspath(os.path.join(os.getcwd(), input_file_path))


# Read the Excel file into a DataFrame
df_nodes = pd.read_excel(full_input_path, sheet_name='Nodes')
df_commodities = pd.read_excel(full_input_path, sheet_name='Commodities')
df_edges = pd.read_excel(full_input_path, sheet_name='Edges')
df_parameter = pd.read_excel(full_input_path, sheet_name='Parameters')
df_supply_values = pd.read_excel(full_input_path, sheet_name='Supply')

### Create input data structure

In [235]:
# Extract nodes, edges and commodities from the DataFrames
Network_nodes = df_nodes['Nodes'].dropna().tolist()
Commodities = df_commodities['Commodities'].dropna().tolist()
Edges = list(zip(df_edges['Source'], df_edges['Destination']))

# Create a nested dictionary for initial capacities
Initial_capacities = {}
for index, row in df_parameter.iterrows():
    commodity = row['Commodity']
    source = row['Source']
    destination = row['Destination']
    initial_capacity = row['initial_capacities']

    edge = f"{source}{destination}"

    if commodity not in Initial_capacities:
        Initial_capacities[commodity] = {}

    Initial_capacities[commodity][edge] = initial_capacity

# Create a nested dictionary for max capacities
Max_capacities = {}
for index, row in df_parameter.iterrows():
    commodity = row['Commodity']
    source = row['Source']
    destination = row['Destination']
    max_capacity = row['max_capacities']

    edge = f"{source}{destination}"

    if commodity not in Max_capacities:
        Max_capacities[commodity] = {}

    Max_capacities[commodity][edge] = max_capacity

# Create a nested dictionary for edge cost
Edge_cost = {}
for index, row in df_parameter.iterrows():
    commodity = row['Commodity']
    source = row['Source']
    destination = row['Destination']
    edge_cost = row['costs_edge']

    edge = f"{source}{destination}"

    if commodity not in Edge_cost:
        Edge_cost[commodity] = {}

    Edge_cost[commodity][edge] = edge_cost

# Create a nested dictionary for new pipelines
Pipe_new_cost = {}
for index, row in df_parameter.iterrows():
    commodity = row['Commodity']
    source = row['Source']
    destination = row['Destination']
    new_cost = row['new_build_cost']

    edge = f"{source}{destination}"

    if commodity not in Pipe_new_cost:
        Pipe_new_cost[commodity] = {}

    Pipe_new_cost[commodity][edge] = new_cost

# Create a nested dictionary for pipeline conversion
Pipe_conv_cost = {}
for index, row in df_parameter.iterrows():
    commodity = row['Commodity']
    source = row['Source']
    destination = row['Destination']
    conv_cost = row['conversion_cost']

    edge = f"{source}{destination}"

    if commodity not in Pipe_conv_cost:
        Pipe_conv_cost[commodity] = {}

    Pipe_conv_cost[commodity][edge] = conv_cost

# Create a nested dictionary for adjusting the capacity when pipeline conversion
Pipe_conv_factor = {}
for index, row in df_parameter.iterrows():
    commodity = row['Commodity']
    source = row['Source']
    destination = row['Destination']
    conv_cap_factor = row['conversion_capacity_factor']

    edge = f"{source}{destination}"

    if commodity not in Pipe_conv_factor:
        Pipe_conv_factor[commodity] = {}

    Pipe_conv_factor[commodity][edge] = conv_cap_factor

# Create a nested dictionary for supply values, skipping 0 and NaN values
Supply_values = {}
for index, row in df_supply_values.iterrows():
    commodity = row['Commodity']
    supply_node = row['Node']
    supply_value = row['Supply']

    if commodity not in Supply_values:
        Supply_values[commodity] = {}

    # Skip 0 and NaN values
    if not pd.isna(supply_value) and supply_value != 0:
        Supply_values[commodity][supply_node] = supply_value

# Create a nested dictionary for node values, skipping 0 and NaN values
Node_values = {}
for index, row in df_supply_values.iterrows():
    commodity = row['Commodity']
    demand_node = row['Node']
    node_value = row['Supply']

    if commodity not in Node_values:
        Node_values[commodity] = {}

    # Skip 0 and NaN values
    #if not pd.isna(node_value) and node_value != 0:
    if not pd.isna(node_value):
        Node_values[commodity][demand_node] = node_value

In [236]:
'''
Create slack nodes for all supply nodes
link a node to supply in case of shortage in the system to all supply nodes
the capacity is infinite but at infinite (super high) cost
'''

# Create a new dictionary for positive values
positive_values_dict = {}

# Iterate through the outer dictionary
for node, values in Node_values.items():
    # Filter out positive values from the inner dictionary
    positive_values = {key: value for key, value in values.items() if value > 0}
    
    # Check if there are positive values before adding to the new dictionary
    if positive_values:
        positive_values_dict[node] = positive_values

#print("Dictionary with positive values:", positive_values_dict)

# Get all keys from the inner dictionaries
all_keys = [key for values in positive_values_dict.values() for key in values.keys()]

# Remove duplicates to get unique keys
unique_keys = list(set(all_keys))

#print("Unique keys:", unique_keys)

# Create a list with names "shortage_" followed by each key
shortage_list = [f'{key}_shortage' for key in unique_keys]

#print("Shortage list:", shortage_list)

#shortage_edges_list = [(key, shortage) for key, shortage in zip(unique_keys, shortage_list)]
shortage_edges_list = [(shortage, key) for key, shortage in zip(shortage_list, unique_keys)]


#print("Edges list:", shortage_edges_list)

shoratege_capacity_dict = {commodity: {f'{shortage}{key}': 10000 for key, shortage in zip(shortage_list, unique_keys)} for commodity in Commodities}
shoratege_max_capacity_dict = shoratege_capacity_dict
#print("Nested dictionary with capacities:", shoratege_capacity_dict)

shoratege_cost_dict = {commodity: {f'{shortage}{key}': 0 for key, shortage in zip(shortage_list, unique_keys)} for commodity in Commodities}
#print("Shortage cost:", shoratege_cost_dict)

In [237]:
shoratege_cost_dict

{'Methane': {'AL_ProdAL_Prod_shortage': 0,
  'ES_LNGES_LNG_shortage': 0,
  'DE_ProdDE_Prod_shortage': 0,
  'NL_ProdNL_Prod_shortage': 0,
  'GR_LNGGR_LNG_shortage': 0,
  'CZ_ProdCZ_Prod_shortage': 0,
  'UK_ProdUK_Prod_shortage': 0,
  'UA_ProdUA_Prod_shortage': 0,
  'RO_ProdRO_Prod_shortage': 0,
  'HR_LNGHR_LNG_shortage': 0,
  'DK_ProdDK_Prod_shortage': 0,
  'NL_LNGNL_LNG_shortage': 0,
  'SI_ProdSI_Prod_shortage': 0,
  'GR_ProdGR_Prod_shortage': 0,
  'SK_ProdSK_Prod_shortage': 0,
  'RS_ProdRS_Prod_shortage': 0,
  'TN_ProdTN_Prod_shortage': 0,
  'RU_ProdRU_Prod_shortage': 0,
  'HR_ProdHR_Prod_shortage': 0,
  'BG_ProdBG_Prod_shortage': 0,
  'FR_LNGFR_LNG_shortage': 0,
  'UK_LNGUK_LNG_shortage': 0,
  'BE_LNGBE_LNG_shortage': 0,
  'AT_ProdAT_Prod_shortage': 0,
  'PL_ProdPL_Prod_shortage': 0,
  'LY_ProdLY_Prod_shortage': 0,
  'ES_ProdES_Prod_shortage': 0,
  'LT_LNGLT_LNG_shortage': 0,
  'BE_ProdBE_Prod_shortage': 0,
  'PL_LNGPL_LNG_shortage': 0,
  'DZ_ProdDZ_Prod_shortage': 0,
  'TR_ProdTR_Prod_shortage': 0,
  'IT_LNGIT_LNG_shortage': 0,
  'NO_ProdNO_Prod_shortage': 0,
  'HU_ProdHU_Prod_shortage': 0,
  'IT_ProdIT_Prod_shortage': 0,
  'PT_LNGPT_LNG_shortage': 0,
  'TR_LNGTR_LNG_shortage': 0,
  'FR_ProdFR_Prod_shortage': 0,
  'IE_ProdIE_Prod_shortage': 0},
 'Hydrogen': {'AL_ProdAL_Prod_shortage': 0,
  'ES_LNGES_LNG_shortage': 0,
  'DE_ProdDE_Prod_shortage': 0,
  'NL_ProdNL_Prod_shortage': 0,
  'GR_LNGGR_LNG_shortage': 0,
  'CZ_ProdCZ_Prod_shortage': 0,
  'UK_ProdUK_Prod_shortage': 0,
  'UA_ProdUA_Prod_shortage': 0,
  'RO_ProdRO_Prod_shortage': 0,
  'HR_LNGHR_LNG_shortage': 0,
  'DK_ProdDK_Prod_shortage': 0,
  'NL_LNGNL_LNG_shortage': 0,
  'SI_ProdSI_Prod_shortage': 0,
  'GR_ProdGR_Prod_shortage': 0,
  'SK_ProdSK_Prod_shortage': 0,
  'RS_ProdRS_Prod_shortage': 0,
  'TN_ProdTN_Prod_shortage': 0,
  'RU_ProdRU_Prod_shortage': 0,
  'HR_ProdHR_Prod_shortage': 0,
  'BG_ProdBG_Prod_shortage': 0,
  'FR_LNGFR_LNG_shortage': 0,
  'UK_LNGUK_LNG_shortage': 0,
  'BE_LNGBE_LNG_shortage': 0,
  'AT_ProdAT_Prod_shortage': 0,
  'PL_ProdPL_Prod_shortage': 0,
  'LY_ProdLY_Prod_shortage': 0,
  'ES_ProdES_Prod_shortage': 0,
  'LT_LNGLT_LNG_shortage': 0,
  'BE_ProdBE_Prod_shortage': 0,
  'PL_LNGPL_LNG_shortage': 0,
  'DZ_ProdDZ_Prod_shortage': 0,
  'TR_ProdTR_Prod_shortage': 0,
  'IT_LNGIT_LNG_shortage': 0,
  'NO_ProdNO_Prod_shortage': 0,
  'HU_ProdHU_Prod_shortage': 0,
  'IT_ProdIT_Prod_shortage': 0,
  'PT_LNGPT_LNG_shortage': 0,
  'TR_LNGTR_LNG_shortage': 0,
  'FR_ProdFR_Prod_shortage': 0,
  'IE_ProdIE_Prod_shortage': 0}}

Print data structure for control

In [238]:
# Print the data for control
#print("Network Nodes:", Network_nodes)
#print("Commodities:", Commodities)
#print("Edges:", Edges)
#print("Initial Capacities:", Initial_capacities)
#print("Max Capacities:", Max_capacities)
#print("Costs per edge Capacities:", Edge_cost)
#print("Costs for new pipelines:", Pipe_new_cost)
#print("Costs for convert pipelines:", Pipe_conv_cost)
#print("Conversion capacity factor:", Pipe_conv_factor)
#print("Node Values:", Node_values)

In [239]:
#check in all nodes are connected via edges

G = nx.Graph()
G.add_edges_from(Edges)

# Check if the graph is connected
if nx.is_connected(G):
    print("The graph is connected.")
else:
    print("The graph is not connected.")

The graph is connected.

In [240]:
#check in all nodes are connected via edges

G = nx.Graph()
G.add_edges_from(Edges)

# Get connected components
connected_components = list(nx.connected_components(G))

# Check if the graph is connected
if len(connected_components) == 1:
    print("The graph is connected.")
else:
    print("The graph is not connected.")
    print("Connected components:")
    for i, component in enumerate(connected_components):
        print(f"Component {i+1}: {component}")

The graph is connected.

In [241]:
# Check if all nodes are connected
if set(Network_nodes) in nx.connected_components(G):
    print("All nodes are connected.")
else:
    print("Not all nodes are connected.")

Not all nodes are connected.

In [242]:
#implement factor to adjust capacity when conversion from methane to hydrogen
#TODO Implement it from the input file and use a correct factor
conversion_factor = Pipe_conv_factor

## Model

### Create model

In [243]:
# Create a new model
model = gp.Model("Grid_Transformation")

### Define parameters

In [244]:
# Parameters
commodities = Commodities  # Commodity types
#real network elements
network_nodes = Network_nodes # Nodes of the system
network_edges = Edges  # Edges
initial_capacities = Initial_capacities # Initial capacities
max_capacities = Max_capacities  # Maximum capacities
costs_edge = Edge_cost  # Cost to transport from node to node
capacity_new_cost = Pipe_new_cost  # Cost to increase capacity
capacity_change_cost = Pipe_conv_cost  # Cost to increase capacity
node_value = Node_values #contains supply and demand values

#slack parameters
slack_nodes = shortage_list
slack_edges = shortage_edges_list
slack_capacities = shoratege_capacity_dict
slack_cost = shoratege_cost_dict

#complete network of the model
all_edges = network_edges + shortage_edges_list

### Define decision variables

In [245]:
# Decision variables
x_flow = {} #flow of commodity on an edge
x_flow_shortage = {}
y_new_cap = {} #new build capacity for a commodity on an edge between two edges
z_conv_cap = {} #capacity of a commodity converted on an edge between two nodes
Change = {} # Binary variable for switching

for commodity in commodities:
    x_flow[commodity] = {}
    x_flow_shortage[commodity] = {}
    y_new_cap[commodity] = {}
    z_conv_cap[commodity] = {}
    Change[commodity] = {}
    for edge in all_edges:
        x_flow[commodity][edge] = model.addVar(vtype=GRB.CONTINUOUS, name=f"x_flow_{commodity}_{edge[0]}_{edge[1]}")
        y_new_cap[commodity][edge] = model.addVar(vtype=GRB.CONTINUOUS, name=f"y_new_cap{commodity}_{edge[0]}_{edge[1]}")
        z_conv_cap[commodity][edge] = model.addVar(vtype=GRB.CONTINUOUS, name=f"z_conv_cap{commodity}_{edge[0]}_{edge[1]}")
        Change[commodity][edge] = model.addVar(vtype=GRB.BINARY, name=f"change_{commodity}_{edge[0]}_{edge[1]}")
    for edge in slack_edges:
        x_flow_shortage[commodity][edge] = model.addVar(vtype=GRB.CONTINUOUS, name=f"x_flow_shortage_{commodity}_{edge[0]}_{edge[1]}")
model.update()

### Define objective and constraints

In [256]:
# Objective function (minimize total transportation cost + cost to increase and convert capacity)
model.setObjective(
    gp.quicksum(x_flow[commodity][edge] * costs_edge[commodity][f"{edge[0]}{edge[1]}"] for commodity in commodities for edge in network_edges) +
    #gp.quicksum(y_new_cap[commodity][edge] * capacity_new_cost[commodity][f"{edge[0]}{edge[1]}"] for commodity in commodities for edge in network_edges) +
    #gp.quicksum(z_conv_cap[commodity][edge] * capacity_change_cost[commodity][f"{edge[0]}{edge[1]}"] for commodity in commodities for edge in network_edges),
    gp.quicksum(x_flow_shortage[commodity][edge] * slack_cost[commodity][f"{edge[0]}{edge[1]}"] for commodity in commodities for edge in slack_edges),
    GRB.MINIMIZE
)

# Constraints

#inflow of a node must equal the outflow of a node
for node in network_nodes:  
    for commodity in commodities:  
        # Flow conservation constraint for the current node and commodity
        model.addConstr(gp.quicksum(x_flow[commodity][edge] for edge in all_edges if edge[1] == node) 
                                    - gp.quicksum(x_flow[commodity][edge] for edge in network_edges if edge[0] == node)
                                    + node_value[commodity][node] 
                                    == 0, f"flow_constraint_{commodity}_{node}")
        #model.addConstr(gp.quicksum(x_flow[commodity][edge] for edge in all_edges if edge[1] == node or edge[0] == node) 
        #                        - gp.quicksum(x_flow[commodity][edge] for edge in network_edges if edge[0] == node or edge[1] == node)
        #                        + node_value[commodity][node] 
        #                        == 0, f"flow_constraint_{commodity}_{node}")


#slack node at the sources to avoid infeasible problems.        
for node in slack_nodes:
    for commodity in commodities: 
        model.addConstr(gp.quicksum(x_flow[commodity][edge] for edge in all_edges if edge[0] == node) >= 0, 
                        f"supply_shortage_{commodity}_{node}")


# Add constraint for equality between x_flow and x_flow_shortage for the same edge
for commodity in commodities:
    for edge in slack_edges:
        if (edge[0], edge[1]) in slack_edges or (edge[1], edge[0]) in slack_edges:
            # Ensure equality for the corresponding edges
            model.addConstr(x_flow[commodity][edge] == x_flow_shortage[commodity][(edge[0], edge[1])], 
                            f"equality_constraint_{commodity}_{edge}")


#Capacity constraint for flow
for commodity in commodities:
    for edge in network_edges:
        model.addConstr(x_flow[commodity][edge] 
                        <= y_new_cap[commodity][edge] + z_conv_cap[commodity][edge] #+ initial_capacities[commodity][f"{edge[0]}{edge[1]}"]
                        , f"used_capacity_{commodity}_{edge[0]}_{edge[1]}")


# Capacity constraint for maximal capacity
for commodity in commodities:
    for edge in network_edges:
        model.addConstr(y_new_cap[commodity][edge] + z_conv_cap[commodity][edge] 
                        <= max_capacities[commodity][f"{edge[0]}{edge[1]}"], f"capacity_{commodity}_{edge[0]}_{edge[1]}")

#Constraints for edge conversion
for edge in network_edges:
    model.addConstr(Change[Commodities[0]][edge] + Change[Commodities[1]][edge] == 1, f"switching_constraint_{edge[0]}_{edge[1]}")

for commodity in commodities:
    for edge in network_edges:
        model.addConstr(initial_capacities[Commodities[0]][f"{edge[0]}{edge[1]}"] * Change[commodity][edge] #* conversion_factor[commodity][node]
                        == z_conv_cap[commodity][edge], f"changed_capacity_{commodity}_{edge[0]}_{edge[1]}")

#Constraing no negative flow
for commodity in commodities:
    for edge in all_edges:
        model.addConstr(x_flow[commodity][edge] >= 0, f"non_negativity_x_{commodity}_{edge[0]}_{edge[1]}")

### Optimize the model

In [257]:
# Optimize the model
model.optimize()

Gurobi Optimizer version 11.0.0 build v11.0.0rc2 (win64 - Windows 11.0 (22621.2))

CPU model: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 5295 rows, 1608 columns and 10720 nonzeros
Model fingerprint: 0xe7a0c086
Variable types: 1226 continuous, 382 integer (382 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+04]
  Objective range  [1e+00, 1e+04]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e-02, 1e+04]
Presolve removed 5270 rows and 1530 columns
Presolve time: 0.01s
Presolved: 25 rows, 78 columns, 155 nonzeros
Variable types: 78 continuous, 0 integer (0 binary)

Root relaxation: infeasible, 23 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 infeasible    0               - infeasible      -     -    0s

Explored 1 nodes (23 simplex iterations) in 0.03 seconds (0.01 work units)
Thread count was 8 (of 8 available processors)

Solution count 0

Model is infeasible
Best objective -, best bound -, gap -

### Results processing

In [248]:
# Print the results
if model.status == GRB.OPTIMAL:
    print("Optimal solution found!")
else:
    print("No optimal solution found.")

No optimal solution found.

In [249]:
# Assuming commodities, edges, x_flow, y_new_cap, Change, and z_conv_cap are defined in your code

# Create lists to store the data
results_data = []
columns = ["Commodity", "Edge", "Flow", "New Capacity", "Switched", "Changed Capacity"]
shortage_data = []
shortage_columns = ["Commodity", "Edge", "Flow"]

# Check if the model has an optimal solution
if model.status == GRB.OPTIMAL:
    for commodity in commodities:
        for edge in network_edges:
            # Append data to the list
            results_data.append([commodity,
                                 edge, 
                                 x_flow[commodity][edge].x, 
                                 y_new_cap[commodity][edge].x, 
                                 Change[commodity][edge].x, 
                                 z_conv_cap[commodity][edge].x])
        for edge in slack_edges:    
            shortage_data.append([commodity, 
                              edge, 
                              x_flow_shortage[commodity][edge].x])
else:
    print("No optimal solution found.")

if model.status == GRB.OPTIMAL:
    # Create a DataFrame
    results_df = pd.DataFrame(results_data, columns=columns)
    shortage_df = pd.DataFrame(shortage_data, columns=shortage_columns)
    # Print the DataFrame
    print(results_df)
    print('********************************')
    print(shortage_df)

No optimal solution found.

In [250]:
#model.write()

In [251]:
methane_rows_df = results_df[results_df['Commodity'].str.contains('Methane', case=False)]
methane_rows_df = methane_rows_df.drop(columns=['New Capacity', 'Switched', 'Changed Capacity'])
methane_rows_df

    Commodity           Edge       Flow
0     Methane   (BE_LNG, BE)  111.37800
1     Methane   (FR_LNG, FR)  322.41000
2     Methane   (GR_LNG, GR)   73.27500
3     Methane   (IT_LNG, IT)  155.83150
4     Methane   (HR_LNG, HR)   25.40200
..        ...            ...        ...
147   Methane  (ES_Prod, ES)    0.44942
148   Methane       (DZ, MA)    0.00000
149   Methane       (DZ, TN)  796.25500
150   Methane       (DK, SE)   10.74700
151   Methane       (RU, BY)    0.00000

[152 rows x 3 columns]

In [252]:
search_element = 'DE'

# Filter rows based on whether the search element is present in 'Column1'
string_df = results_df[results_df['Edge'].astype(str).str.contains(search_element, case=False, na=False)]

# Display the resulting DataFrame
string_df

,Commodity,Edge,Flow,New Capacity,Switched,Changed Capacity
14,Methane,"(DE_Prod, DE)",47.618980,10000.0,0.0,0.0
29,Methane,"(BE, DE)",311.239292,10000.0,0.0,0.0
32,Methane,"(NL, DE)",0.000000,10000.0,0.0,0.0
33,Methane,"(DE, BE)",0.000000,10000.0,0.0,0.0
34,Methane,"(DE, NL)",0.000000,10000.0,0.0,0.0
35,Methane,"(DE, AT)",400.051114,10000.0,0.0,0.0
36,Methane,"(DE, CH)",0.000000,10000.0,0.0,0.0
37,Methane,"(DE, FR)",0.000000,10000.0,0.0,0.0
38,Methane,"(DE, DK)",25.966824,10000.0,0.0,0.0
39,Methane,"(DE, PL)",95.815562,10000.0,0.0,0.0
40,Methane,"(DE, CZ)",81.129347,10000.0,0.0,0.0
41,Methane,"(DE, LU)",3.136188,10000.0,0.0,0.0
42,Methane,"(AT, DE)",0.000000,10000.0,0.0,0.0
50,Methane,"(CH, DE)",0.000000,10000.0,0.0,0.0
60,Methane,"(DK, DE)",0.000000,0.0,0.0,0.0
61,Methane,"(PL, DE)",0.000000,10000.0,0.0,0.0
62,Methane,"(CZ, DE)",0.000000,10000.0,0.0,0.0
97,Methane,"(RU, DE)",0.000000,10000.0,0.0,0.0
122,Methane,"(NO, DE)",1092.345763,10000.0,0.0,0.0
166,Hydrogen,"(DE_Prod, DE)",-0.000000,0.0,1.0,10000.0
181,Hydrogen,"(BE, DE)",0.000000,0.0,1.0,10000.0
184,Hydrogen,"(NL, DE)",0.000000,0.0,1.0,10000.0
185,Hydrogen,"(DE, BE)",0.000000,0.0,1.0,10000.0
186,Hydrogen,"(DE, NL)",0.000000,0.0,1.0,10000.0
187,Hydrogen,"(DE, AT)",0.000000,0.0,1.0,10000.0
188,Hydrogen,"(DE, CH)",0.000000,0.0,1.0,10000.0
189,Hydrogen,"(DE, FR)",0.000000,0.0,1.0,10000.0
190,Hydrogen,"(DE, DK)",0.000000,0.0,1.0,10000.0
191,Hydrogen,"(DE, PL)",0.000000,0.0,1.0,10000.0
192,Hydrogen,"(DE, CZ)",0.000000,0.0,1.0,10000.0
193,Hydrogen,"(DE, LU)",0.000000,0.0,1.0,10000.0
194,Hydrogen,"(AT, DE)",0.000000,0.0,1.0,10000.0
202,Hydrogen,"(CH, DE)",0.000000,0.0,1.0,10000.0
212,Hydrogen,"(DK, DE)",0.000000,0.0,1.0,10000.0
213,Hydrogen,"(PL, DE)",0.000000,0.0,1.0,10000.0
214,Hydrogen,"(CZ, DE)",0.000000,0.0,1.0,10000.0
249,Hydrogen,"(RU, DE)",0.000000,0.0,1.0,10000.0
274,Hydrogen,"(NO, DE)",0.000000,0.0,1.0,10000.0

In [253]:
shortage_df

methane_shortage_df = shortage_df[shortage_df['Commodity'].str.contains('Methane', case=False)]
methane_shortage_df

   Commodity                         Edge  Flow
0    Methane  (AL_Prod, AL_Prod_shortage)   0.0
1    Methane    (ES_LNG, ES_LNG_shortage)   0.0
2    Methane  (DE_Prod, DE_Prod_shortage)   0.0
3    Methane  (NL_Prod, NL_Prod_shortage)   0.0
4    Methane    (GR_LNG, GR_LNG_shortage)   0.0
5    Methane  (CZ_Prod, CZ_Prod_shortage)   0.0
6    Methane  (UK_Prod, UK_Prod_shortage)   0.0
7    Methane  (UA_Prod, UA_Prod_shortage)   0.0
8    Methane  (RO_Prod, RO_Prod_shortage)   0.0
9    Methane    (HR_LNG, HR_LNG_shortage)   0.0
10   Methane  (DK_Prod, DK_Prod_shortage)   0.0
11   Methane    (NL_LNG, NL_LNG_shortage)   0.0
12   Methane  (SI_Prod, SI_Prod_shortage)   0.0
13   Methane  (GR_Prod, GR_Prod_shortage)   0.0
14   Methane  (SK_Prod, SK_Prod_shortage)   0.0
15   Methane  (RS_Prod, RS_Prod_shortage)   0.0
16   Methane  (TN_Prod, TN_Prod_shortage)   0.0
17   Methane  (RU_Prod, RU_Prod_shortage)   0.0
18   Methane  (HR_Prod, HR_Prod_shortage)   0.0
19   Methane  (BG_Prod, BG_Prod_shortage)   0.0
20   Methane    (FR_LNG, FR_LNG_shortage)   0.0
21   Methane    (UK_LNG, UK_LNG_shortage)   0.0
22   Methane    (BE_LNG, BE_LNG_shortage)   0.0
23   Methane  (AT_Prod, AT_Prod_shortage)   0.0
24   Methane  (PL_Prod, PL_Prod_shortage)   0.0
25   Methane  (LY_Prod, LY_Prod_shortage)   0.0
26   Methane  (ES_Prod, ES_Prod_shortage)   0.0
27   Methane    (LT_LNG, LT_LNG_shortage)   0.0
28   Methane  (BE_Prod, BE_Prod_shortage)   0.0
29   Methane    (PL_LNG, PL_LNG_shortage)   0.0
30   Methane  (DZ_Prod, DZ_Prod_shortage)   0.0
31   Methane  (TR_Prod, TR_Prod_shortage)   0.0
32   Methane    (IT_LNG, IT_LNG_shortage)   0.0
33   Methane  (NO_Prod, NO_Prod_shortage)   0.0
34   Methane  (HU_Prod, HU_Prod_shortage)   0.0
35   Methane  (IT_Prod, IT_Prod_shortage)   0.0
36   Methane    (PT_LNG, PT_LNG_shortage)   0.0
37   Methane    (TR_LNG, TR_LNG_shortage)   0.0
38   Methane  (FR_Prod, FR_Prod_shortage)   0.0
39   Methane  (IE_Prod, IE_Prod_shortage)   0.0

In [254]:
methane_rows_df.to_excel("output1.xlsx")