In [3]:
import pandas as pd
import os

In [47]:
# Function to calculate cost
def calculate_cost(row):
    # Base cost per km
    cost = row['Distance [km]'] * cost_factor_transportation
    
    # Add additional costs for Suez or Panama
    if pd.notna(row['Suez or Panama']):
        if 'Suez' in row['Suez or Panama']:
            cost += cost_factor_suez
        elif 'Panama' in row['Suez or Panama']:
            cost += cost_factor_panama
    
    return cost

# Function to create the new dataframe based on the "From" column for liquefaction cost
def create_LNG_liquefaction_df(df, factor):
    # Step 1: Create a new dataframe with unique "From" values and the corresponding "To" column
    unique_from_df = pd.DataFrame(df['From'].unique(), columns=['From'])
    
    # Step 2: Adjust the "From" column by removing "_LNG" and place the original "From" values in the "To" column
    unique_from_df['To'] = unique_from_df['From']
    unique_from_df['From'] = unique_from_df['From'].str.replace('_LNG', '')
    
    # Step 3: Add the "Cost" column with the value of cost_factor_liquification
    unique_from_df['Cost'] = factor
    
    return unique_from_df

# Function to create the new dataframe based on the "To" column for regasification cost
def create_LNG_regasification_df(df, factor):
    # Step 1: Create a new dataframe with unique "To" values and the corresponding "To" column
    unique_from_df = pd.DataFrame(df['To'].unique(), columns=['To'])
    
    # Step 2: Adjust the "To" column by removing "_LNG" and place the original "To" values in the "From" column
    unique_from_df['From'] = unique_from_df['To']
    unique_from_df['To'] = unique_from_df['To'].str.replace('_LNG', '')
    
    # Step 3: Add the "Cost" column with the value of cost_factor_liquification
    unique_from_df['Cost'] = factor
    
    return unique_from_df

## Import Data

In [9]:
# Specify the path to your Excel file
input_file_path = os.path.join('..', '..','01_data', '01_input_data', '02_processed')
excel_file_name = '\\Gas_Import_Russian_Invasion.xlsx'
#data_case_russia_peak_hour.xlsx

input_file_path  = input_file_path + excel_file_name
full_input_path = os.path.abspath(os.path.join(os.getcwd(), input_file_path))

In [10]:
df_LNG_global = pd.read_excel(full_input_path, sheet_name='global_LNG_connections')

In [11]:
df_LNG_global

,From,To,GWh/d [capacity],GWh/a,TWh/a,Distance [miles],Distance [km],Suez or Panama,Comment,Unnamed: 9,Unnamed: 10,Unnamed: 11,distance from https://sea-distances.org/advanced
0,USA_LNG,SA_LNG,NaN,NaN,0,5323,8566.540762,NaN,Rio,NaN,NaN,NaN,Qatar from Doha
1,USA_LNG,AF_LNG,NaN,NaN,0,6194,9968.279820,NaN,Port Harcourt,NaN,NaN,NaN,USA from Houston
2,USA_LNG,CN_LNG,NaN,NaN,0,10194,16405.657812,Panama,Dalian,NaN,NaN,NaN,Trinidad from Point Fortin
3,USA_LNG,JS_LNG,NaN,NaN,0,9266,14912.186117,Panama,Tokyo,NaN,NaN,NaN,ME from Das Island (UAE)
4,USA_LNG,IN_LNG,NaN,NaN,0,9568,15398.208156,Suez,Okha,NaN,NaN,NaN,AF from Port Harcourt (Nigeria)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,RU_LNG,EE_LNG,NaN,NaN,0,3259,5244.853719,NaN,Talinn,NaN,NaN,NaN,NaN
210,RU_LNG,FI_LNG,NaN,NaN,0,3259,5244.853719,NaN,Inkoo,NaN,NaN,NaN,NaN
211,RU_LNG,DE_LNG,NaN,NaN,0,2730,4393.510479,NaN,Wilhelmshaven,NaN,NaN,NaN,NaN
212,RU_LNG,IE_LNG,NaN,NaN,0,3077,4951.953020,NaN,Cork,NaN,NaN,NaN,NaN
213,RU_LNG,LV_LNG,NaN,NaN,0,3199,5148.293049,NaN,Riga,NaN,NaN,NaN,NaN

In [36]:
cost_factor_transportation = 2
cost_factor_liquefaction = 2000
cost_factor_regasification = 2000
cost_factor_panama = 2000
cost_factor_suez = 2000

In [49]:
# Apply the function to each row and create a new column 'Cost per km'
df_LNG_global['Cost per Route'] = df_LNG_global.apply(calculate_cost, axis=1)

# Create a new dataframe with the relevant columns
df_cost_per_km = df_LNG_global[['From', 'To', 'Distance [km]', 'Suez or Panama', 'Cost per Route']]

# Display the new dataframe
df_cost_per_km

        From      To  Distance [km] Suez or Panama  Cost per Route
0    USA_LNG  SA_LNG    8566.540762            NaN       17.133082
1    USA_LNG  AF_LNG    9968.279820            NaN       19.936560
2    USA_LNG  CN_LNG   16405.657812         Panama     2032.811316
3    USA_LNG  JS_LNG   14912.186117         Panama     2029.824372
4    USA_LNG  IN_LNG   15398.208156           Suez     2030.796416
..       ...     ...            ...            ...             ...
209   RU_LNG  EE_LNG    5244.853719            NaN       10.489707
210   RU_LNG  FI_LNG    5244.853719            NaN       10.489707
211   RU_LNG  DE_LNG    4393.510479            NaN        8.787021
212   RU_LNG  IE_LNG    4951.953020            NaN        9.903906
213   RU_LNG  LV_LNG    5148.293049            NaN       10.296586

[214 rows x 5 columns]

In [39]:
# Get LNG liquefaction cost df
LNG_liquefaction_df = create_LNG_liquefaction_df(df_LNG_global, cost_factor_liquefaction)
# Get LNG regasification cost df
LNG_regasification_df = create_LNG_regasification_df(df_LNG_global, cost_factor_regasification)

In [41]:
LNG_regasification_df

    To    From  Cost
0   SA  SA_LNG  2000
1   AF  AF_LNG  2000
2   CN  CN_LNG  2000
3   JS  JS_LNG  2000
4   IN  IN_LNG  2000
5   AS  AS_LNG  2000
6   EG  EG_LNG  2000
7   BE  BE_LNG  2000
8   FR  FR_LNG  2000
9   GR  GR_LNG  2000
10  IT  IT_LNG  2000
11  HR  HR_LNG  2000
12  LT  LT_LNG  2000
13  NL  NL_LNG  2000
14  PL  PL_LNG  2000
15  PT  PT_LNG  2000
16  ES  ES_LNG  2000
17  TR  TR_LNG  2000
18  UK  UK_LNG  2000
19  EE  EE_LNG  2000
20  FI  FI_LNG  2000
21  DE  DE_LNG  2000
22  IE  IE_LNG  2000
23  LV  LV_LNG  2000

In [50]:
df_cost_per_km.to_excel("inputs.xlsx")