# Script to get the differences of emissions between scenarios

This jupyter notebook contains all routine calculations of the emission differences in Europe compared to another scenario. 

**Authors:** Johannes Giehl (jfg.eco@cbs.dk)

## Import packages

In [1]:
#import
import pandas as pd
from cost_and_gas_source_share_functions import *
from emission_calculation_functions import *

## Define path to data

In [2]:
#path for output and input data
#for gas shares per country
data_file_path = os.path.join('..', '..', '01_data', '02_output_data', '02_unidirectional_results', '01_paper_IAEE', '02_prepared_results')
full_data_file_path = os.path.abspath(os.path.join(os.getcwd(), data_file_path))
#for demand per country
demand_data_path = os.path.join('..', '..', '01_data', '01_input_data', '02_processed', '01_paper_IAEE')
full_demand_data_path = os.path.abspath(os.path.join(os.getcwd(), demand_data_path))
#emission factors
emission_factors_data_path = os.path.join('..', '..', '01_data', '01_input_data', '02_processed')
emission_factors_file_name = '\emission_factors_natural_gas.xlsx'
emission_factors_path = emission_factors_data_path + emission_factors_file_name
full_emission_factors_path = os.path.abspath(os.path.join(os.getcwd(), emission_factors_path))

#specify the output file
output_file_name = '\emission_differences.xlsx'
output_file_path = data_file_path + output_file_name
full_output_file_path = os.path.abspath(os.path.join(os.getcwd(), output_file_path))

## Load te data

In [3]:
#get all cost dfs from the excels in the prepared results folder
#shares of gas sources per node
dfs = load_excel_sheets_by_name(full_data_file_path, "costs_shares", sheet_name="shares")
#demand of the nodes
dfs_demand = load_excel_sheets_by_name(full_demand_data_path, "inputs_IAEE_2025_run", sheet_name="Supply")
#emission factors imports
dfs_emission_factors_im = pd.read_excel(full_emission_factors_path, sheet_name="Emission_Factors_Import", index_col=0)
#emission factors domestic
dfs_emission_factors_dom = pd.read_excel(full_emission_factors_path, sheet_name="Emission_Factors_Domestic", index_col=0)

In [4]:
#get df with information of EU membership
dfs_EU_countries = dfs_emission_factors_im.iloc[:, 0:1]

## Prepare individual dataframes

In [5]:
df_names = list(dfs.keys())
df_names

['costs_shares_IAEE_2025_run_2021',
 'costs_shares_IAEE_2025_run_2024',
 'costs_shares_IAEE_2025_run_2024_inv',
 'costs_shares_IAEE_2025_run_2024_plus_no_QA',
 'costs_shares_IAEE_2025_run_2024_plus_NO_reduced',
 'costs_shares_IAEE_2025_run_2024_plus_no_USA',
 'costs_shares_IAEE_2025_run_2024_with_RU',
 'costs_shares_IAEE_2025_run_2035_AP',
 'costs_shares_IAEE_2025_run_2035_SP']

In [6]:
df_shares_IAEE_2025_run_2021 = dfs['costs_shares_IAEE_2025_run_2021']
df_shares_IAEE_2025_run_2024 = dfs['costs_shares_IAEE_2025_run_2024']
df_shares_IAEE_2025_run_2024_inv = dfs['costs_shares_IAEE_2025_run_2024_inv']
df_shares_IAEE_2025_run_2024_plus_no_QA = dfs['costs_shares_IAEE_2025_run_2024_plus_no_QA']
df_shares_IAEE_2025_run_2024_plus_NO_reduced = dfs['costs_shares_IAEE_2025_run_2024_plus_NO_reduced']
df_shares_IAEE_2025_run_2024_plus_no_USA = dfs['costs_shares_IAEE_2025_run_2024_plus_no_USA']
df_shares_IAEE_2025_run_2024_with_RU = dfs['costs_shares_IAEE_2025_run_2024_with_RU']
df_shares_IAEE_2025_run_2035_AP = dfs['costs_shares_IAEE_2025_run_2035_AP']
df_shares_IAEE_2025_run_2035_SP = dfs['costs_shares_IAEE_2025_run_2035_SP']

In [7]:
df_names_demand = list(dfs_demand.keys())
df_names_demand

['inputs_IAEE_2025_run_2021',
 'inputs_IAEE_2025_run_2024',
 'inputs_IAEE_2025_run_2024_inv',
 'inputs_IAEE_2025_run_2024_plus_no_QA',
 'inputs_IAEE_2025_run_2024_plus_NO_reduced',
 'inputs_IAEE_2025_run_2024_plus_no_USA',
 'inputs_IAEE_2025_run_2024_with_RU',
 'inputs_IAEE_2025_run_2035_AP',
 'inputs_IAEE_2025_run_2035_SP']

In [8]:
df_demand_IAEE_2025_run_2021                 = dfs_demand['inputs_IAEE_2025_run_2021']
df_demand_IAEE_2025_run_2024                 = dfs_demand['inputs_IAEE_2025_run_2024']
df_demand_IAEE_2025_run_2024_inv             = dfs_demand['inputs_IAEE_2025_run_2024_inv']
df_demand_IAEE_2025_run_2024_plus_no_QA      = dfs_demand['inputs_IAEE_2025_run_2024_plus_no_QA']
df_demand_IAEE_2025_run_2024_plus_NO_reduced = dfs_demand['inputs_IAEE_2025_run_2024_plus_NO_reduced']
df_demand_IAEE_2025_run_2024_plus_no_USA     = dfs_demand['inputs_IAEE_2025_run_2024_plus_no_USA']
df_demand_IAEE_2025_run_2024_with_RU         = dfs_demand['inputs_IAEE_2025_run_2024_with_RU']
df_demand_IAEE_2025_run_2035_AP              = dfs_demand['inputs_IAEE_2025_run_2035_AP']
df_demand_IAEE_2025_run_2035_SP              = dfs_demand['inputs_IAEE_2025_run_2035_SP']

In [9]:
#filter the dataframes so that they contain only demand
df_demand_2021_filtered = filter_negative_supply(df_demand_IAEE_2025_run_2021, "Methane")
df_demand_2024_filtered = filter_negative_supply(df_demand_IAEE_2025_run_2024, "Methane")
df_demand_2024_inv_filtered = filter_negative_supply(df_demand_IAEE_2025_run_2024_inv, "Methane")
df_demand_2024_no_QA_filtered = filter_negative_supply(df_demand_IAEE_2025_run_2024_plus_no_QA, "Methane")
df_demand_2024_NO_red_filtered = filter_negative_supply(df_demand_IAEE_2025_run_2024_plus_NO_reduced, "Methane")
df_demand_2024_no_USA_filtered = filter_negative_supply(df_demand_IAEE_2025_run_2024_plus_no_USA, "Methane")
df_demand_2024_with_RU_filtered = filter_negative_supply(df_demand_IAEE_2025_run_2024_with_RU, "Methane")
df_demand_2035_AP_filtered = filter_negative_supply(df_demand_IAEE_2025_run_2035_AP, "Methane")
df_demand_2035_SP_filtered = filter_negative_supply(df_demand_IAEE_2025_run_2035_SP, "Methane")

## Calculate emissions

In [10]:
#import emissions
df_import_emissions_2021 = calculate_emissions_per_country(dfs_emission_factors_im, df_shares_IAEE_2025_run_2021, df_demand_2021_filtered)
df_import_emissions_2024 = calculate_emissions_per_country(dfs_emission_factors_im, df_shares_IAEE_2025_run_2024, df_demand_2024_filtered)
df_import_emissions_2024_inv = calculate_emissions_per_country(dfs_emission_factors_im, df_shares_IAEE_2025_run_2024_inv, df_demand_2024_inv_filtered)
df_import_emissions_2024_no_QA = calculate_emissions_per_country(dfs_emission_factors_im, df_shares_IAEE_2025_run_2024_plus_no_QA, df_demand_2024_no_QA_filtered)
df_import_emissions_2024_NO_red = calculate_emissions_per_country(dfs_emission_factors_im, df_shares_IAEE_2025_run_2024_plus_NO_reduced, df_demand_2024_NO_red_filtered)
df_import_emissions_2024_no_USA = calculate_emissions_per_country(dfs_emission_factors_im, df_shares_IAEE_2025_run_2024_plus_no_USA, df_demand_2024_no_USA_filtered)
df_import_emissions_2024_with_RU = calculate_emissions_per_country(dfs_emission_factors_im, df_shares_IAEE_2025_run_2024_with_RU, df_demand_2024_with_RU_filtered)
df_import_emissions_2035_AP = calculate_emissions_per_country(dfs_emission_factors_im, df_shares_IAEE_2025_run_2035_AP, df_demand_2035_AP_filtered)
df_import_emissions_2035_SP = calculate_emissions_per_country(dfs_emission_factors_im, df_shares_IAEE_2025_run_2035_SP, df_demand_2035_SP_filtered)

In [11]:
#domestic emissions
df_domestic_emissions_2021 = calculate_domestic_emissions(dfs_emission_factors_dom, df_shares_IAEE_2025_run_2021, df_demand_2021_filtered)
df_domestic_emissions_2024 = calculate_domestic_emissions(dfs_emission_factors_dom, df_shares_IAEE_2025_run_2024, df_demand_2024_filtered)
df_domestic_emissions_2024_inv = calculate_domestic_emissions(dfs_emission_factors_dom, df_shares_IAEE_2025_run_2024_inv, df_demand_2024_inv_filtered)
df_domestic_emissions_2024_no_QA = calculate_domestic_emissions(dfs_emission_factors_dom, df_shares_IAEE_2025_run_2024_plus_no_QA, df_demand_2024_no_QA_filtered)
df_domestic_emissions_2024_NO_red = calculate_domestic_emissions(dfs_emission_factors_dom, df_shares_IAEE_2025_run_2024_plus_NO_reduced, df_demand_2024_NO_red_filtered)
df_domestic_emissions_2024_no_USA = calculate_domestic_emissions(dfs_emission_factors_dom, df_shares_IAEE_2025_run_2024_plus_no_USA, df_demand_2024_no_USA_filtered)
df_domestic_emissions_2024_with_RU = calculate_domestic_emissions(dfs_emission_factors_dom, df_shares_IAEE_2025_run_2024_with_RU, df_demand_2024_with_RU_filtered)
df_domestic_emissions_2035_AP = calculate_domestic_emissions(dfs_emission_factors_dom, df_shares_IAEE_2025_run_2035_AP, df_demand_2035_AP_filtered)
df_domestic_emissions_2035_SP = calculate_domestic_emissions(dfs_emission_factors_dom, df_shares_IAEE_2025_run_2035_SP, df_demand_2035_SP_filtered)

In [12]:
#emissions for al Europen countries
df_total_emissions_2021 = combine_total_emissions(df_import_emissions_2021, df_domestic_emissions_2021)
df_total_emissions_2024 = combine_total_emissions(df_import_emissions_2024, df_domestic_emissions_2024)
df_total_emissions_2024_inv = combine_total_emissions(df_import_emissions_2024_inv, df_domestic_emissions_2024_inv)
df_total_emissions_2024_no_QA = combine_total_emissions(df_import_emissions_2024_no_QA, df_domestic_emissions_2024_no_QA)
df_total_emissions_2024_NO_red = combine_total_emissions(df_import_emissions_2024_NO_red, df_domestic_emissions_2024_NO_red)
df_total_emissions_2024_no_USA = combine_total_emissions(df_import_emissions_2024_no_USA, df_domestic_emissions_2024_no_USA)
df_total_emissions_2024_with_RU = combine_total_emissions(df_import_emissions_2024_with_RU, df_domestic_emissions_2024_with_RU)
df_total_emissions_2035_AP = combine_total_emissions(df_import_emissions_2035_AP, df_domestic_emissions_2035_AP)
df_total_emissions_2035_SP = combine_total_emissions(df_import_emissions_2035_SP, df_domestic_emissions_2035_SP)

In [13]:
totals_2021 = calculate_total_emissions(df_total_emissions_2021)
totals_2024 = calculate_total_emissions(df_total_emissions_2024)
totals_2024_inv = calculate_total_emissions(df_total_emissions_2024_inv)
totals_2024_no_QA = calculate_total_emissions(df_total_emissions_2024_no_QA)
totals_2024_NO_red = calculate_total_emissions(df_total_emissions_2024_NO_red)
totals_2024_no_USA = calculate_total_emissions(df_total_emissions_2024_no_USA)
totals_2024_with_RU = calculate_total_emissions(df_total_emissions_2024_with_RU)
totals_2035_AP = calculate_total_emissions(df_total_emissions_2035_AP)
totals_2035_SP = calculate_total_emissions(df_total_emissions_2035_SP)

In [14]:
df_emissions_summary = build_emissions_summary(
    totals_2021=totals_2021,
    totals_2024=totals_2024,
    totals_2024_inv=totals_2024_inv,
    totals_2024_no_QA=totals_2024_no_QA,
    totals_2024_NO_red=totals_2024_NO_red,
    totals_2024_no_USA=totals_2024_no_USA,
    totals_2024_with_RU=totals_2024_with_RU,
    totals_2035_AP=totals_2035_AP,
    totals_2035_SP=totals_2035_SP
)

In [15]:
df_emissions_summary

,Total_Import_Emissions,Total_Domestic_Emissions,Total_Emissions
Scenario,,,
2021,8.913135e+07,2.576184e+06,9.170754e+07
2024,8.072830e+07,2.458983e+06,8.318729e+07
2024_inv,8.072830e+07,2.573275e+06,8.330158e+07
2024_no_QA,8.072830e+07,2.458983e+06,8.318729e+07
2024_NO_red,8.072830e+07,2.274622e+06,8.300292e+07
2024_no_USA,5.595215e+07,2.440676e+06,5.839282e+07
2024_with_RU,6.532837e+07,2.448130e+06,6.777650e+07
2035_AP,3.008950e+07,1.404284e+06,3.149379e+07
2035_SP,6.475702e+07,2.235377e+06,6.699240e+07

In [16]:
#emissions for all EU countries

In [17]:
df_EU_total_emissions_2021 = combine_total_emissions(
    import_emissions_df=df_import_emissions_2021,
    domestic_emissions_df=df_domestic_emissions_2021,
    only_EU=True,
    dfs_EU_countries=dfs_EU_countries
)
df_EU_total_emissions_2024 = combine_total_emissions(
    import_emissions_df=df_import_emissions_2024,
    domestic_emissions_df=df_domestic_emissions_2024,
    only_EU=True,
    dfs_EU_countries=dfs_EU_countries
)
df_EU_total_emissions_2024_inv = combine_total_emissions(
    import_emissions_df=df_import_emissions_2024_inv,
    domestic_emissions_df=df_domestic_emissions_2024_inv,
    only_EU=True,
    dfs_EU_countries=dfs_EU_countries
)
df_EU_total_emissions_2024_no_QA = combine_total_emissions(
    import_emissions_df=df_import_emissions_2024_no_QA,
    domestic_emissions_df=df_domestic_emissions_2024_no_QA,
    only_EU=True,
    dfs_EU_countries=dfs_EU_countries
)
df_EU_total_emissions_2024_NO_red = combine_total_emissions(
    import_emissions_df=df_import_emissions_2024_NO_red,
    domestic_emissions_df=df_domestic_emissions_2024_NO_red,
    only_EU=True,
    dfs_EU_countries=dfs_EU_countries
)
df_EU_total_emissions_2024_no_USA = combine_total_emissions(
    import_emissions_df=df_import_emissions_2024_no_USA,
    domestic_emissions_df=df_domestic_emissions_2024_no_USA,
    only_EU=True,
    dfs_EU_countries=dfs_EU_countries
)
df_EU_total_emissions_2024_with_RU = combine_total_emissions(
    import_emissions_df=df_import_emissions_2024_with_RU,
    domestic_emissions_df=df_domestic_emissions_2024_with_RU,
    only_EU=True,
    dfs_EU_countries=dfs_EU_countries
)
df_EU_total_emissions_2035_AP = combine_total_emissions(
    import_emissions_df=df_import_emissions_2035_AP,
    domestic_emissions_df=df_domestic_emissions_2035_AP,
    only_EU=True,
    dfs_EU_countries=dfs_EU_countries
)
df_EU_total_emissions_2035_SP = combine_total_emissions(
    import_emissions_df=df_import_emissions_2035_SP,
    domestic_emissions_df=df_domestic_emissions_2035_SP,
    only_EU=True,
    dfs_EU_countries=dfs_EU_countries
)

In [18]:
totals_EU_2021 = calculate_total_emissions(df_EU_total_emissions_2021)
totals_EU_2024 = calculate_total_emissions(df_EU_total_emissions_2024)
totals_EU_2024_inv = calculate_total_emissions(df_EU_total_emissions_2024_inv)
totals_EU_2024_no_QA = calculate_total_emissions(df_EU_total_emissions_2024_no_QA)
totals_EU_2024_NO_red = calculate_total_emissions(df_EU_total_emissions_2024_NO_red)
totals_EU_2024_no_USA = calculate_total_emissions(df_EU_total_emissions_2024_no_USA)
totals_EU_2024_with_RU = calculate_total_emissions(df_EU_total_emissions_2024_with_RU)
totals_EU_2035_AP = calculate_total_emissions(df_EU_total_emissions_2035_AP)
totals_EU_2035_SP = calculate_total_emissions(df_EU_total_emissions_2035_SP)

In [19]:
df_EU_emissions_summary = build_emissions_summary(
    totals_2021=totals_EU_2021,
    totals_2024=totals_EU_2024,
    totals_2024_inv=totals_EU_2024_inv,
    totals_2024_no_QA=totals_EU_2024_no_QA,
    totals_2024_NO_red=totals_EU_2024_NO_red,
    totals_2024_no_USA=totals_EU_2024_no_USA,
    totals_2024_with_RU=totals_EU_2024_with_RU,
    totals_2035_AP=totals_EU_2035_AP,
    totals_2035_SP=totals_EU_2035_SP
)

In [20]:
df_EU_emissions_summary

,Total_Import_Emissions,Total_Domestic_Emissions,Total_Emissions
Scenario,,,
2021,5.853781e+07,1.087288e+06,5.962510e+07
2024,6.340625e+07,8.000043e+05,6.420626e+07
2024_inv,5.946425e+07,9.142723e+05,6.037852e+07
2024_no_QA,6.316025e+07,8.000043e+05,6.396025e+07
2024_NO_red,6.676206e+07,7.900772e+05,6.755213e+07
2024_no_USA,4.434761e+07,7.830896e+05,4.513070e+07
2024_with_RU,5.771038e+07,8.131457e+05,5.852353e+07
2035_AP,2.507752e+07,2.242781e+05,2.530180e+07
2035_SP,5.109332e+07,7.187089e+05,5.181203e+07

## Export results

In [21]:
# Export to Excel with multiple sheets
with pd.ExcelWriter(full_output_file_path, engine='openpyxl') as writer:
    df_emissions_summary.to_excel(writer, index=True, sheet_name='Emissions_Europe')
    df_EU_emissions_summary.to_excel(writer, index=True, sheet_name='Emissions_EU')